name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
        pnpm: [7, 8, 9]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup node | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
