name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test

      - name: Build docker image
        run: docker build -t delanhese-devops-ci-api:latest .
